version: '3.8'
services:
  backend:
    build: .
    container_name: salon-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: ["node", "index.js"]

  frontend:
    image: nginx:alpine
    container_name: salon-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80 